// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
        int greaterThan50 = 0;
        int lessThanOrEqualTo50 = 0;
        for (int i = 0; i < N; i++) {
            double randomValue = Math.random();
            if (randomValue > 0.5) {
                greaterThan50++;
            } else {
                lessThanOrEqualTo50++;
            }
        }
        System.out.println("> 0.5: " + greaterThan50 + " times");
        System.out.println("<= 0.5: " + lessThanOrEqualTo50 + " times");
		
        if (lessThanOrEqualTo50 == 0) {
            System.out.println("Ratio: undefined");
        } else {
            double ratio = (double) greaterThan50 / lessThanOrEqualTo50;
            System.out.println("Ratio: " + ratio);
        }
	}
}
